

-- tabelas

-- segmercado (categorias onde podemos classificar empresas), cliente


CREATE TABLE SEGMERCADO
(
ID NUMBER(5),
DESCRICAO VARCHAR2(100)
);

CREATE TABLE CLIENTE
(
ID NUMBER(5),
RAZAO_SOCIAL VARCHAR2(100),
CNPJ VARCHAR2(20),
SEGMERCADO_ID NUMBER(5),
DATA_INCLUSAO DATE,
FATURAMENTO_PREVISTO NUMBER(10,2),
CATEGORIA VARCHAR2(20)
);

ALTER TABLE SEGMERCADO ADD CONSTRAINT SEGMERCADO_ID_PK 
PRIMARY KEY (ID);

ALTER TABLE CLIENTE ADD CONSTRAINT CLIENTE_ID_PK 
PRIMARY KEY (ID);

ALTER TABLE CLIENTE ADD CONSTRAINT CLIENTE_SEGMERCADO_ID
FOREIGN KEY (SEGMERCADO_ID) REFERENCES SEGMERCADO (ID);

--
CREATE TABLE PRODUTO_EXERCICIO
(
COD VARCHAR2(5),
DESCRICAO VARCHAR2(100),
CATEGORIA VARCHAR2(100)
);

CREATE TABLE PRODUTO_VENDA_EXERCICIO
(
ID NUMBER(5),
COD_PRODUTO VARCHAR2(5),
DATA DATE,
QUANTIDADE FLOAT,
PRECO FLOAT,
VALOR_TOTAL FLOAT,
PERCENTUAL_IMPOSTO FLOAT
);

-- pks 
ALTER TABLE PRODUTO_EXERCICIO ADD CONSTRAINT PRODUTO_EXERCICIO_COD_PKPRIMARY PRIMARY KEY (COD);

ALTER TABLE USERX.PRODUTO_VENDA_EXERCICIO ADD CONSTRAINT PRODUTO_VENDA_EXERCICIO_ID_PKPRIMARY PRIMARY KEY (ID);

-- fk
ALTER TABLE PRODUTO_VENDA_EXERCICIO ADD CONSTRAINT 
PRODUTO_VENDA_EXERCICIO_PRODUTO_EXERCICIO_COD FOREIGN KEY (COD_PRODUTO) REFERENCES PRODUTO_EXERCICIO (COD);

